[package]
name = "codeforces"
version = "0.1.0"
edition = "2021"

[features]
not_codeforces = []

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
